from django.urls import path
from . import views
urlpatterns = [
    path('', views.shoplist, name='shoplist'),
    path('<int:pk>/', views.shopdetail, name='shopdetail'),
    path('mypage/', views.shopmyPage, name='mypage'),
    path('create/', views.create, name='itemcreate'),
    path('category/<slug:slug>/', views.category_view, name='category_view'),
    path('search/', views.search, name='search'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('mypage/order_status/', views.order_status, name='order_status'),
    path('mypage/order_history/', views.order_history, name='order_history'),
    path('mypage/wishlist/', views.wishlist, name='wishlist'),
    path('mypage/contact/', views.contact, name='contact'),
    path('mypage/contact_history/', views.contact_history, name='contact_history'),
    path('mypage/admincontact/', views.admincontact, name='admincontact'),
    path('mypage/reply/<int:comment_id>/', views.reply_comment, name='reply_comment'),
    path('mypage/create/', views.create, name='create'),
    path('comment/<int:pk>/updatecomment/', views.updatecomment, name='updatecomment'),
    path('comment/<int:pk>/deletecomment/', views.deletecomment, name='deletecomment'),
    path('wishlist/add/<int:pk>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:pk>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('cartlist/add/<int:pk>/', views.add_to_cartlist, name='add_to_cartlist'),
    path('cartlist/remove/<int:pk>/', views.remove_from_cartlist, name='remove_from_cartlist'),
    path('cartlist/', views.cartlist, name='cartlist'),
    ]