# Generated by Django 5.2.4 on 2025-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="starting_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
