# Generated by Django 5.2.4 on 2025-07-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_post_updated_alter_post_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uploaded_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="modified",
            field=models.DateTimeField(null=True),
        ),
    ]
