# Generated by Django 5.2.4 on 2025-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_post_uploaded_image_alter_post_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated",
        ),
        migrations.AddField(
            model_name="post",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
