# Generated by Django 5.2.4 on 2025-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_post_starting_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="order_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
