# Generated by Django 5.2.4 on 2025-07-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_post_created_remove_post_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="size",
            field=models.IntegerField(null=True),
        ),
    ]
