# Generated by Django 5.2.4 on 2025-08-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_post_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="bid_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
