# Generated by Django 5.2.4 on 2025-08-11 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_post_price_alter_post_size_cartlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="shop.post",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["id"], name="shop_commen_id_50ba28_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post"], name="shop_commen_post_id_436302_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent"], name="shop_commen_parent__a53d92_idx"
            ),
        ),
    ]
