# Generated by Django 5.2.4 on 2025-08-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_post_order_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="order_count",
            new_name="purchase_count",
        ),
    ]
