# Generated by Django 5.2.4 on 2025-07-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_post_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="size",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
