# Generated by Django 5.2.4 on 2025-08-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_rename_order_count_post_purchase_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="purchase_count",
        ),
    ]
