# Generated by Django 5.2.4 on 2025-07-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_post_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
