# Generated by Django 5.2.4 on 2025-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_post_purchase_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_purchases", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
