# Generated by Django 5.2.4 on 2025-08-12 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_storestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="storestats",
            name="last_updated",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="storestats",
            name="today_purchases",
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AlterField(
            model_name="storestats",
            name="total_purchases",
            field=models.PositiveIntegerField(default=847342),
        ),
    ]
