# Generated by Django 5.2.4 on 2025-08-12 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_storestats_last_updated_storestats_today_purchases_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storestats",
            name="last_updated",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
