# Generated by Django 5.2.4 on 2025-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_storestats_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storestats",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="storestats",
            name="last_purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
