# Generated by Django 5.2.4 on 2025-08-12 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_storestats_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storestats",
            name="last_purchase_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
