# Generated by Django 5.2.4 on 2025-08-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_chatmessage_bid_amount"),
        ("shop", "0011_alter_storestats_last_purchase_date"),
    ]

    operations = []
