# Generated by Django 5.2.5 on 2025-08-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_category_post_modified_post_category"),
        ("shop", "0012_category_post_bottom_top_post_chest_post_chongjang_and_more"),
    ]

    operations = []
