# Generated by Django 5.2.4 on 2025-08-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_merge_20250812_1640"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="bid_amount",
        ),
        migrations.RemoveField(
            model_name="post",
            name="buyer",
        ),
    ]
