# Generated by Django 5.2.4 on 2025-08-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_remove_chatmessage_bid_amount_remove_post_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
